<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>fileTypes</key>
        <array>
                <string>block</string>
                <string>item</string>
                <string>list</string>
                <string>page</string>
                <string>region</string>
        </array>
        <key>name</key>
        <string>HTML (JSON-T)</string>
        <key>patterns</key>
        <array>
                <false/>
        </array>
        <key>repository</key>
        <dict>
                <key>block-comments</key>
                <array>
                        <dict>
                                <key>begin</key>
                                <string>\{##BEGIN\}</string>
                                <key>end</key>
                                <string>\{##END\}</string>
                                <key>name</key>
                                <string>comment.block.jsont</string>
                        </dict>
                </array>
                <key>constants</key>
                <array>
                        <dict>
                                <key>match</key>
                                <string>(?&lt;=\.)(space|tab|newline|meta-left|meta-right)</string>
                                <key>name</key>
                                <string>constant.character.jsont</string>
                        </dict>
                </array>
                <key>constructs</key>
                <array>
                        <dict>
                                <key>begin</key>
                                <string>\{(\.)</string>
                                <key>beginCaptures</key>
                                <dict>
                                        <key>1</key>
                                        <dict>
                                                <key>name</key>
                                                <string>punctuation.separator.jsont</string>
                                        </dict>
                                </dict>
                                <key>end</key>
                                <string>\}</string>
                                <key>name</key>
                                <string>meta.directive.jsont</string>
                                <key>patterns</key>
                                <array>
                                        <dict>
                                                <key>include</key>
                                                <string>#constants</string>
                                        </dict>
                                        <dict>
                                                <key>include</key>
                                                <string>#directives</string>
                                        </dict>
                                        <dict>
                                                <key>include</key>
                                                <string>#predicates</string>
                                        </dict>
                                        <dict>
                                                <key>include</key>
                                                <string>#cursor</string>
                                        </dict>
                                        <dict>
                                                <key>include</key>
                                                <string>#definitions</string>
                                        </dict>
                                        <dict>
                                                <key>include</key>
                                                <string>#squarespace</string>
                                        </dict>
                                </array>
                        </dict>
                </array>
                <key>cursor</key>
                <array>
                        <dict>
                                <key>match</key>
                                <string>(@((?=\\B)|index))</string>
                                <key>name</key>
                                <string>support.class.jsont</string>
                        </dict>
                </array>
                <key>definitions</key>
                <dict>
                        <key>patterns</key>
                        <array>
                                <dict>
                                        <key>match</key>
                                        <string>\\@(?=[a-zA-Z0-9_-]+)</string>
                                        <key>name</key>
                                        <string>punctuation.definition.variable.jsont</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>(?&lt;=@)[a-zA-Z0-9_-]+(?=(\\s|\\||\\.|\\}))</string>
                                        <key>name</key>
                                        <string>variable.other.jsont</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>(?&lt;=\\s)\\"[a-zA-Z0-9_-]+\\"(?=\\})</string>
                                        <key>name</key>
                                        <string>string.quoted.jsont</string>
                                </dict>
                        </array>
                </dict>
                <key>directives</key>
                <dict>
                        <key>patterns</key>
                        <array>
                                <dict>
                                        <key>match</key>
                                        <string>(?&lt;=\{\.)(section|repeated section|if|end)</string>
                                        <key>name</key>
                                        <string>keyword.control.jsont</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>(?&lt;=\{\.)(or|alternates with)</string>
                                        <key>name</key>
                                        <string>keyword.control.jsont</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>(?&lt;=\{\.)var</string>
                                        <key>name</key>
                                        <string>storage.type.jsont</string>
                                </dict>
                        </array>
                </dict>
                <key>formatters</key>
                <dict>
                        <key>patterns</key>
                        <array>
                                <dict>
                                        <key>match</key>
                                        <string>\\|(?=\\w)</string>
                                        <key>name</key>
                                        <string>punctuation.separator.formatter.jsont</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>\\s[0-9]+</string>
                                        <key>name</key>
                                        <string>constant.numeric.jsont</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>\\s[a-zA-Z0-9_-]+\\.?[a-zA-Z0-9_-]+</string>
                                        <key>name</key>
                                        <string>string.unquoted.jsont</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>(html((?![a-z\\-])|-attr-value)|json|js-string|raw|str|template-file|url-param-value)</string>
                                        <key>name</key>
                                        <string>support.function.without-args.jsont</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>(activate-twitter-links|apply|comment(-link|-count|s)|count|height|html(attr|tag)|image-meta|item-classes|json-pretty|like-button|product-(price|status)|safe|slugify|smartypants|social-button((?!\\-)|-inline)|timesince|url-encode|width)</string>
                                        <key>name</key>
                                        <string>support.function.without-args.jsont.sqsp</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>(date|pluralize|truncate|video)</string>
                                        <key>name</key>
                                        <string>support.function.with-args.jsont.sqsp</string>
                                </dict>
                        </array>
                </dict>
                <key>line-comments</key>
                <array>
                        <dict>
                                <key>begin</key>
                                <string>\{#</string>
                                <key>end</key>
                                <string>\}</string>
                                <key>name</key>
                                <string>comment.line.number-sign.jsont</string>
                        </dict>
                </array>
                <key>predicates</key>
                <dict>
                        <key>patterns</key>
                        <array>
                                <dict>
                                        <key>match</key>
                                        <string>(?&lt;=\\{\\.)Debug(?=\\?)</string>
                                        <key>name</key>
                                        <string>entity.name.function.jsont</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>(?&lt;=\\{\\.)(collection((?![a-z\\-])|TypeNameEquals)|comments|disqus|equal|even((?![a-z\\-])|t)|excerpt|external-link|folder|index|location|main-image|odd|plural|promote(map|embed|image|code|quote|twitter|link|video|foursquare|instagram|form)|singular|video)(?=\\?)</string>
                                        <key>name</key>
                                        <string>entity.name.function.jsont.sqsp</string>
                                </dict>
                                <dict>
                                        <key>match</key>
                                        <string>(?&lt;=[a-zA-Z0-9_-])\\?</string>
                                        <key>name</key>
                                        <string>keyword.control.jsont</string>
                                </dict>
                        </array>
                </dict>
                <key>squarespace</key>
                <dict>
                        <key>patterns</key>
                        <array>
                                <dict>
                                        <key>match</key>
                                        <string>(postItemInjectCode|squarespace((?!\\-)|-headers|-post-entry|-footers))</string>
                                        <key>name</key>
                                        <string>support.class.jsont.sqsp</string>
                                </dict>
                                <dict>
                                        <key>comment</key>
                                        <string>Squarespace object properties</string>
                                        <key>match</key>
                                        <string>\\b(main-content|page\\-(classes|id))\\b</string>
                                        <key>name</key>
                                        <string>support.constant.jsont.sqsp</string>
                                </dict>
                                <dict>
                                        <key>comment</key>
                                        <string>Top-level Squarespace page objects</string>
                                        <key>match</key>
                                        <string>\\b(authenticatedAccount|calendarView|collection|empty(\\b|Folder)|items|shareButtons|shoppingCart|showCart|template|website(\\b|Settings))\\b</string>
                                        <key>name</key>
                                        <string>entity.name.function.jsont.sqsp</string>
                                </dict>
                        </array>
                </dict>
                <key>variables</key>
                <array>
                        <dict>
                                <key>begin</key>
                                <string>\{(?!\.)</string>
                                <key>end</key>
                                <string>\}</string>
                                <key>name</key>
                                <string>meta.substitution.jsont</string>
                                <key>patterns</key>
                                <array>
                                        <dict>
                                                <key>include</key>
                                                <string>#cursor</string>
                                        </dict>
                                        <dict>
                                                <key>include</key>
                                                <string>#definitions</string>
                                        </dict>
                                        <dict>
                                                <key>include</key>
                                                <string>#squarespace</string>
                                        </dict>
                                        <dict>
                                                <key>include</key>
                                                <string>#formatters</string>
                                        </dict>
                                </array>
                        </dict>
                </array>
        </dict>
        <key>scopeName</key>
        <string>text.html.jsont</string>
        <key>uuid</key>
        <string>51987eb6-dcfd-4c22-bcee-373bf7aad1be</string>
</dict>
</plist>
