<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>HTML (JSON-T)</string>

  <key>fileTypes</key>
  <array>
    <string>block</string>
    <string>item</string>
    <string>list</string>
    <string>page</string>
    <string>region</string>
  </array>

  <key>foldingStartMarker</key>
  <string>{\.(if|section|repeated)}[^({.end})]+</string>
  <key>foldingStopMarker</key>
  <string>(?x){\.(end)}</string>

  <key>patterns</key>
  <array>
    <dict>
      <key>comment</key>
      <string>Include HTML grammar as a starting point.</string>
      <key>include</key>
      <string>text.html.basic</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#block-comments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#line-comments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#constructs</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#variables</string>
    </dict>
  </array>

  <key>repository</key>
  <dict>
    <key>line-comments</key>
    <dict>
      <key>name</key>
      <string>comment.line.number-sign.jsont</string>
      <key>begin</key>
      <string>{#</string>
      <key>end</key>
      <string>}</string>
    </dict>

    <key>block-comments</key>
    <dict>
      <key>name</key>
      <string>comment.block.jsont</string>
      <key>begin</key>
      <string>{##BEGIN}</string>
      <key>end</key>
      <string>{##END}</string>
    </dict>

    <key>variables</key>
    <dict>
      <key>name</key>
      <string>meta.substitution.jsont</string>
      <key>begin</key>
      <string>\{(?!\.)</string>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#cursor</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#definitions</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#squarespace</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#formatters</string>
        </dict>
      </array>
    </dict>

    <key>constructs</key>
    <dict>
      <key>name</key>
      <string>meta.directive.jsont</string>
      <key>begin</key>
      <string>\{(\.)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <string>punctuation.separator.jsont</string>
      </dict>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#constants</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#directives</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#predicates</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#cursor</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#definitions</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#squarespace</string>
        </dict>
      </array>
    </dict>

    <key>constants</key>
    <dict>
      <key>name</key>
      <string>constant.character.jsont</string>
      <key>match</key>
      <string>(?<=\.)(space|tab|newline|meta-left|meta-right)</string>
    </dict>

    <key>directives</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>keyword.control.jsont</string>
          <key>match</key>
          <string>(?<=\{\.)(section|repeated section|if|end)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.control.jsont</string>
          <key>match</key>
          <string>(?<=\{\.)(or|alternates with)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>storage.type.jsont</string>
          <key>match</key>
          <string>(?<=\{\.)var</string>
        </dict>
      </array>
    </dict>

    <key>predicates</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>entity.name.function.jsont</string>
          <key>match</key>
          <string>(?<=\{\.)Debug(?=\?)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.name.function.jsont.sqsp</string>
          <key>match</key>
          <string>(?<=\{\.)(collection((?![a-z\-])|TypeNameEquals)|comments|disqus|equal|even((?![a-z\-])|t)|excerpt|external-link|folder|location|main-image|odd|plural|promote(map|embed|image|code|quote|twitter|link|video|foursquare|instagram|form)|singular|video)(?=\?)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.control.jsont</string>
          <key>match</key>
          <string>(?<=[a-zA-Z0-9_-])\?</string>
        </dict>
      </array>
    </dict>

    <key>definitions</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>punctuation.definition.variable.jsont</string>
          <key>match</key>
          <string>@(?=[a-zA-Z0-9_-]+)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>variable.other.jsont</string>
          <key>match</key>
          <string>(?<=@)[a-zA-Z0-9_-]+(?=(\s|\||\.|\}))</string>
        </dict>
        <dict>
          <key>name</key>
          <string>string.quoted.jsont</string>
          <key>match</key>
          <string>(?<=\s)\"[a-zA-Z0-9_-]+\"(?=\})</string>
        </dict>
      </array>
    </dict>

    <key>cursor</key>
    <dict>
      <key>name</key>
      <string>support.class.jsont</string>
      <key>match</key>
      <string>(@((?=\B)|index))</string>
    </dict>

    <key>squarespace</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>support.class.jsont.sqsp</string>
          <key>match</key>
          <string>(postItemInjectCode|squarespace((?!\-)|-headers|-post-entry|-footers))</string>
        </dict>
        <dict>
          <key>comment</key>
          <string>Squarespace object properties</string>
          <key>name</key>
          <string>support.constant.jsont.sqsp</string>
          <key>match</key>
          <string>\b(main-content|page\-(classes|id))\b</string>
        </dict>
        <dict>
          <key>comment</key>
          <string>Top-level Squarespace page objects</string>
          <key>name</key>
          <string>entity.name.function.jsont.sqsp</string>
          <key>match</key>
          <string>\b(authenticatedAccount|calendarView|collection|empty(\b|Folder)|items|shareButtons|shoppingCart|showCart|template|website(\b|Settings))\b</string>
        </dict>
      </array>
    </dict>

    <key>formatters</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>punctuation.separator.formatter.jsont</string>
          <key>match</key>
          <string>\|(?=\w)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.numeric.jsont</string>
          <key>match</key>
          <string>\s[0-9]+</string>
        </dict>
        <dict>
          <key>name</key>
          <string>string.unquoted.jsont</string>
          <key>match</key>
          <string>\s[a-zA-Z0-9_-]+\.?[a-zA-Z0-9_-]+</string>
        </dict>
        <dict>
          <key>name</key>
          <string>support.function.without-args.jsont</string>
          <key>match</key>
          <string>(html((?![a-z\-])|-attr-value)|json|js-string|raw|str|template-file|url-param-value)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>support.function.without-args.jsont.sqsp</string>
          <key>match</key>
          <string>(activate-twitter-links|apply|comment(-link|-count|s)|count|height|html(attr|tag)|image-meta|item-classes|json-pretty|like-button|product-(price|status)|safe|slugify|smartypants|social-button((?!\-)|-inline)|timesince|url-encode|width)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>support.function.with-args.jsont.sqsp</string>
          <key>match</key>
          <string>(date|pluralize|truncate|video)</string>
        </dict>
      </array>
  </dict>
  <key>scopeName</key>
  <string>text.html.jsont</string>

  <key>uuid</key>
  <string>12f1ad07-29ae-4b1d-9a95-0712a46d5ec6</string>
</dict>
