<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>block</string>
		<string>item</string>
		<string>list</string>
		<string>page</string>
		<string>region</string>
	</array>
	<key>injections</key>
	<dict>
		<key>L: text.html.jsont</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directives</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>name</key>
	<string>HTML (JSON-T)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Include HTML grammar as a starting point.</string>
			<key>include</key>
			<string>text.html.basic</string>
			<key>scopeName</key>
			<string>text.html</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arguments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.jsont</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\s)([a-zA-Z0-9_\x{7f}-\x{ff}\.-]*)</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.(space|tab|newline|meta-left|meta-right)</string>
					<key>name</key>
					<string>constant.character.jsont</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(?&lt;=[\s\[\(\{:,])(?:true|false|null|none)(?=[\s\)\]\}\,])</string>
					<key>name</key>
					<string>constant.language.jsont</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[\s\[\(\{:,]|\.\.|\*\*)[0-9]+(?:\.[0-9]+)?(?=[\s\)\]\}\,]|\.\.|\*\*)</string>
					<key>name</key>
					<string>constant.numeric.jsont</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\%[a-zA-Z\%]</string>
					<key>name</key>
					<string>constant.other.jsont</string>
				</dict>
			</array>
		</dict>
		<key>definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Cursor</string>
					<key>match</key>
					<string>(@((?=\\B)|index))</string>
					<key>name</key>
					<string>support.class.jsont</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\@(?=[a-zA-Z0-9_-]+)</string>
					<key>name</key>
					<string>punctuation.definition.variable.jsont</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=@)[a-zA-Z0-9_-]+(?=(\\s|\\||\\.|\\}))</string>
					<key>name</key>
					<string>variable.other.jsont</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>begin</key>
			<string>\{(?!#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.jsont</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.jsont</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#predicates</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definitions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatters-wargs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.(section|repeated section|if|end)</string>
					<key>name</key>
					<string>keyword.control.jsont</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.(or|alternates with)</string>
					<key>name</key>
					<string>keyword.control.jsont</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.var</string>
					<key>name</key>
					<string>storage.type.jsont</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definitions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatters-wargs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>formatters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.without-args.jsont</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\\'\"@])(\|(?:html((?![a-z\-])|-attr-value)|json|js-string|raw|str|template-file|url-param-value))(?=[\s\|\]\}\):,]|\.\.|\*\*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.without-args.jsont.sqsp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\\'\"@])(\|(?:activate-twitter-links|comment(?:-link|-count|s)|count|height|html(?:attr|tag)|image-meta|item-classes|json-pretty|like-button|product-(?:price|status)|safe|slugify|smartypants|social-button(?:(?!\-)|-inline)|timesince|url-encode|width))(?=[\s\|\]\}\):,]|\.\.|\*\*)</string>
				</dict>
			</array>
		</dict>
		<key>formatters-wargs</key>
		<dict>
			<key>begin</key>
			<string>(\|(?:apply|date|pluralize|truncate|video))((?:\s|\/))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.with-args.jsont.sqsp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.jsont.sqsp</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.function.arguments.jsont.sqsp</string>
			<key>end</key>
			<string>(?:\||(?!\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.jsont.sqsp</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#arguments</string>
				</dict>
			</array>
		</dict>
		<key>line-comments</key>
		<dict>
			<key>begin</key>
			<string>\{#(?!(?:#BEGIN|#END))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.jsont</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.jsont</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.line.number-sign.jsont</string>
		</dict>
		<key>objects</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.jsont.sqsp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=[\s\{\[\(:,])(postItemInjectCode|squarespace((?!\\-)|-headers|-post-entry|-footers))(?=[\s\}\[\]\(\)\.\|,:])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.jsont</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=[\s\{\[\(:,])([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)(?=[\s\}\[\]\(\)\.\|,:])</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bitwise.jsont</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\s)(&amp;|\||\^)(?=\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.jsont</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\s)((?:!|=)=|&lt;=?|&gt;=?|i(?:s|n))(?=\s)</string>
				</dict>
			</array>
		</dict>
		<key>predicates</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.jsont</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsont</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((?:\.|\.or\s)Debug)(\?)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.jsont.sqsp</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsont.sqsp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((?:\.|(?&lt;=\.or\s))(?:collection(?:(?![a-z\\-])|TypeNameEquals)|comments|disqus|equal|even(?:(?![a-z\\-])|t)|excerpt|external-link|folder|index|location|main-image|odd|plural|promote(?:map|embed|image|code|quote|twitter|link|video|foursquare|instagram|form)|singular|video))(\?)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#definitions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatters-wargs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#formatters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>properties</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.property.jsont</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.jsont.sqsp</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Squarespace object properties</string>
					<key>match</key>
					<string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}])(\.)(main-content|page-(?:classes|id))(?=[\.\s\|\[\)\]\}:,])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.property.jsont</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.jsont.sqsp</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Top-level Squarespace page objects</string>
					<key>match</key>
					<string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}])(\.)(authenticatedAccount|calendarView|collection|empty(\\b|Folder)|items|shareButtons|shoppingCart|showCart|template|website(\\b|Settings))(?=[\.\s\|\[\)\]\}:,])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.property.jsont</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.jsont</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}])(\.)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)(?=[\.\s\|\[\)\]\}:,])</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:(?&lt;!\\\\)|(?&lt;=\\\\\\\\))\'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.jsont</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?:(?&lt;!\\\\)|(?&lt;=\\\\\\\\))\'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.jsont</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.jsont</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:(?&lt;!\\\\)|(?&lt;=\\\\\\\\))"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.jsont</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?:(?&lt;!\\\\)|(?&lt;=\\\\\\\\))"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.jsont</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.jsont</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.jsont</string>
	<key>uuid</key>
	<string>51987eb6-dcfd-4c22-bcee-373bf7aad1be</string>
</dict>
</plist>
